misc:
  hide_status_window: false
  noise_on_completion: false
  print_to_terminal: true
model_options:
  api:
    api_key: null
    base_url: https://api.openai.com/v1
    model: whisper-1
  common:
    initial_prompt: null
    language: en
    temperature: 0.0
  local:
    compute_type: float16
    condition_on_previous_text: true
    device: auto
    model: large-v3
    model_path: null
    vad_filter: true
  use_api: false
post_processing:
  add_trailing_space: false
  input_method: pynput
  remove_capitalization: true
  remove_trailing_period: true
  writing_key_press_delay: 0.005
recording_options:
  activation_key: ctrl+shift+space
  input_backend: auto
  min_duration: 100
  recording_mode: hold_to_record
  sample_rate: 16000
  silence_duration: 900
  sound_device: null
